# footprint: [[-0.25, -0.25], [-0.25, 0.25], [0.25, 0.25], [0.25, -0.25]]
# footprint_padding: 0.01

# robot_base_frame: base_link
# update_frequency: 4.0
# publish_frequency: 3.0
# transform_tolerance: 0.5

# resolution: 0.05

# obstacle_range: 3.5
# raytrace_range: 4.0

# #layer definitions
# static:
#     map_topic: /map
#     subscribe_to_updates: true

# obstacles_laser:
#     observation_sources: laser
#     laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

# inflation:
#     inflation_radius: 1.0
#     cost_scaling_factor: 3.0

# global_frame: map
# rolling_window: false
# track_unknown_space: true

# plugins:
#   - {name: static,                  type: "costmap_2d::StaticLayer"}
#   - {name: inflation,               type: "costmap_2d::InflationLayer"}
  

global_frame: map
rolling_window: false
track_unknown_space: true

plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}

# footprint: [[-0.15, -0.23], [-0.15, 0.23], [0.15, 0.23], [0.15, -0.23]]
footprint: [[-0.15, -0.15], [-0.15, 0.15], [0.15, 0.15], [0.15, -0.15]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5
default_tolerance: 0.04

resolution: 0.05

obstacle_range: 3.0
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
    inflation_radius: 1.0